config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  "start_date": "2024-09-01"
  "end_date": "2024-09-30"

seeds:
  jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  jaffle_shop:
    # Bronze Layer - Direct source mappings with minimal transformation
    bronze:
      +materialized: view
      +tags: ['bronze']
      +schema: 'bronze'
    # Silver Layer - Business logic transformations and enrichment
    silver:
      +materialized: view
      +tags: ['silver']
      +schema: 'silver'
    # Gold Layer - Analysis-ready data for reporting and BI
    gold:
      +materialized: table
      +tags: ['gold']
      +schema: 'gold'
    # Legacy staging layer (being migrated to bronze/silver)
    staging:
      +materialized: view
      +schema: 'staging'
    # Legacy marts layer (being migrated to gold)
    marts:
      +materialized: table
      +schema: 'marts'
